// =============================================================================
// src/models/QuotationModel.js
// Data Access Layer — cotizaciones, cotizacion_detalles, cotizaciones_correlativo
// (Section 3.5.2 — Data Dictionary + Section 3.6.1 — Sequence Diagram)
//
// CRITICAL — Atomic Serial Number Generation (HU03 / RNF10):
//   generateCorrelativo() wraps the counter increment inside a database
//   transaction with SELECT ... FOR UPDATE. This row-level lock serializes
//   concurrent requests, guaranteeing that no two quotations ever receive the
//   same serial number, even under high concurrency. See Section 3.11.3.
// =============================================================================

'use strict';

const { pool } = require('../config/db'); // Shared MySQL connection pool

// Valid quotation states as defined in the state machine (Section 3.6.2)
const VALID_STATES = [
  'Pendiente',
  'En revision',
  'Aprobada internamente',
  'Enviada al cliente',
  'Aceptada',
  'Rechazada',
  'Archivada',
];

// State-transition matrix: maps each current state to the states it can move to.
// The service layer consults this before executing any status change.
const STATE_TRANSITIONS = {
  'Pendiente':             ['En revision', 'Archivada'],
  'En revision':           ['Aprobada internamente', 'Rechazada', 'Pendiente', 'Archivada'],
  'Aprobada internamente': ['Enviada al cliente', 'Archivada'],
  'Enviada al cliente':    ['Aceptada', 'Rechazada', 'Archivada'],
  'Aceptada':              ['Archivada'],
  'Rechazada':             ['Pendiente', 'Archivada'],
  'Archivada':             [], // Terminal state — no further transitions
};

const QuotationModel = {

  // ---------------------------------------------------------------------------
  // generateCorrelativo
  // ATOMIC OPERATION — must be called inside a managed transaction.
  //
  // Acquires an exclusive row lock on the current year's counter row
  // (SELECT ... FOR UPDATE), increments ultimo_nro by 1, releases the lock
  // on COMMIT, and returns the formatted serial string COT-YYYY-NNNN.
  //
  // If no row exists for the current year, one is inserted with ultimo_nro=1
  // and the serial COT-YYYY-0001 is returned.
  //
  // @param   {PoolConnection} connection - An active pool connection (in transaction)
  // @returns {string}                    - Formatted serial, e.g. "COT-2026-0042"
  // ---------------------------------------------------------------------------
  async generateCorrelativo(connection) {
    const currentYear = new Date().getFullYear(); // e.g. 2026

    // Attempt to lock the existing row for this year.
    // FOR UPDATE acquires an exclusive row lock; concurrent callers block here
    // until the lock is released by COMMIT or ROLLBACK.
    const [rows] = await connection.execute(
      'SELECT ultimo_nro FROM cotizaciones_correlativo WHERE anio = ? FOR UPDATE',
      [currentYear]
    );

    let nextNumber; // The new sequential number to assign

    if (rows.length === 0) {
      // First quotation of this calendar year — insert the counter row
      await connection.execute(
        'INSERT INTO cotizaciones_correlativo (anio, ultimo_nro) VALUES (?, 1)',
        [currentYear]
      );
      nextNumber = 1; // First serial of the year
    } else {
      // Increment the existing counter atomically
      nextNumber = rows[0].ultimo_nro + 1;
      await connection.execute(
        'UPDATE cotizaciones_correlativo SET ultimo_nro = ? WHERE anio = ?',
        [nextNumber, currentYear]
      );
    }

    // Format: COT-YYYY-NNNN (zero-padded to 4 digits; supports up to 9999/year)
    const serial = `COT-${currentYear}-${String(nextNumber).padStart(4, '0')}`;
    return serial;
  },

  // ---------------------------------------------------------------------------
  // create
  // Insert the parent cotizaciones record. Must be called inside a transaction.
  //
  // @param   {PoolConnection} connection - Active transactional connection
  // @param   {Object}         data       - Quotation fields
  // @returns {number}                    - insertId of the new quotation
  // ---------------------------------------------------------------------------
  async create(connection, data) {
    const sql = `
      INSERT INTO cotizaciones
        (numero_correlativo, id_cliente, id_ejecutivo, descripcion,
         monto_total, moneda, estado, observaciones, fecha_emision, fecha_validez)
      VALUES
        (?, ?, ?, ?, ?, ?, 'Pendiente', ?, ?, ?)
    `;

    const [result] = await connection.execute(sql, [
      data.numero_correlativo, // COT-YYYY-NNNN generated by generateCorrelativo
      data.id_cliente,
      data.id_ejecutivo,
      data.descripcion,
      data.monto_total    || null,
      data.moneda         || 'USD',
      data.observaciones  || null,
      data.fecha_emision,
      data.fecha_validez  || null,
    ]);

    return result.insertId; // Primary key of the newly created quotation
  },

  // ---------------------------------------------------------------------------
  // createDetalles
  // Insert multiple line-item rows (cotizacion_detalles) for a quotation.
  // Uses a single multi-value INSERT for efficiency.
  //
  // @param   {PoolConnection} connection    - Active transactional connection
  // @param   {number}         id_cotizacion - Parent quotation ID
  // @param   {Array<Object>}  detalles      - Array of line items
  // ---------------------------------------------------------------------------
  async createDetalles(connection, id_cotizacion, detalles) {
    if (!detalles || detalles.length === 0) {
      return; // No line items to insert; the quotation header was already saved
    }

    // Build parameterized placeholders: (?, ?, ?, ?, ?, ?) for each row
    const placeholders = detalles.map(() => '(?, ?, ?, ?, ?, ?)').join(', ');

    // Flatten the values array: [id_cot, id_prod, desc, qty, price, subtotal, id_cot, ...]
    const values = detalles.flatMap((item) => {
      const subtotal = parseFloat(
        (parseFloat(item.cantidad) * parseFloat(item.precio_unitario)).toFixed(2)
      );

      return [
        id_cotizacion,
        item.id_producto     || null,       // optional catalog reference
        item.descripcion_item,
        parseFloat(item.cantidad),
        parseFloat(item.precio_unitario),
        subtotal,                           // persisted computed value
      ];
    });

    const sql = `
      INSERT INTO cotizacion_detalles
        (id_cotizacion, id_producto, descripcion_item, cantidad, precio_unitario, subtotal)
      VALUES
        ${placeholders}
    `;

    await connection.execute(sql, values);
  },

  // ---------------------------------------------------------------------------
  // findById
  // Retrieve a complete quotation with client and executive info.
  // Uses a regular pool connection (no transaction needed for reads).
  //
  // @param   {number}       id - Quotation primary key
  // @returns {Object|null}
  // ---------------------------------------------------------------------------
  async findById(id) {
    // Fetch the parent quotation row with JOIN data
    const sqlHeader = `
      SELECT
        c.id,
        c.numero_correlativo,
        c.id_cliente,
        cl.razon_social  AS cliente_nombre,
        cl.nit           AS cliente_nit,
        c.id_ejecutivo,
        u.nombre_completo AS ejecutivo_nombre,
        c.descripcion,
        c.monto_total,
        c.moneda,
        c.estado,
        c.pdf_ruta,
        c.observaciones,
        c.fecha_emision,
        c.fecha_validez,
        c.aprobado_por,
        ap.nombre_completo AS aprobador_nombre,
        c.fecha_aprobacion,
        c.obs_aprobacion,
        c.creado_en,
        c.actualizado_en
      FROM cotizaciones c
      INNER JOIN clientes  cl ON cl.id = c.id_cliente
      INNER JOIN usuarios  u  ON u.id  = c.id_ejecutivo
      LEFT  JOIN usuarios  ap ON ap.id = c.aprobado_por   -- Jefe who approved/rejected
      WHERE c.id = ?
      LIMIT 1
    `;

    const [headerRows] = await pool.execute(sqlHeader, [id]);

    if (!headerRows[0]) {
      return null; // Quotation not found
    }

    const quotation = headerRows[0];

    // Fetch associated line items
    const sqlDetalles = `
      SELECT
        d.id,
        d.id_producto,
        p.codigo         AS producto_codigo,
        d.descripcion_item,
        d.cantidad,
        d.precio_unitario,
        d.subtotal
      FROM cotizacion_detalles d
      LEFT JOIN productos p ON p.id = d.id_producto
      WHERE d.id_cotizacion = ?
      ORDER BY d.id ASC
    `;

    const [detallesRows] = await pool.execute(sqlDetalles, [id]);

    quotation.detalles = detallesRows; // Attach line items to the parent object

    return quotation;
  },

  // ---------------------------------------------------------------------------
  // findAll
  // List quotations with optional filters (Section 3.10 — GET /api/cotizaciones).
  //
  // @param   {Object}       filters - { estado, id_cliente, id_ejecutivo, desde, hasta, q }
  // @returns {Array<Object>}
  // ---------------------------------------------------------------------------
  async findAll(filters = {}) {
    const conditions = []; // WHERE clauses built dynamically
    const values     = []; // Bound parameters corresponding to each "?"

    if (filters.estado) {
      conditions.push('c.estado = ?');
      values.push(filters.estado);
    }

    if (filters.id_cliente) {
      conditions.push('c.id_cliente = ?');
      values.push(parseInt(filters.id_cliente, 10));
    }

    if (filters.id_ejecutivo) {
      conditions.push('c.id_ejecutivo = ?');
      values.push(parseInt(filters.id_ejecutivo, 10));
    }

    if (filters.desde) {
      conditions.push('c.fecha_emision >= ?');
      values.push(filters.desde); // Expected format: YYYY-MM-DD
    }

    if (filters.hasta) {
      conditions.push('c.fecha_emision <= ?');
      values.push(filters.hasta);
    }

    if (filters.q) {
      // Partial match on correlativo or client name (case-insensitive via utf8mb4)
      conditions.push('(c.numero_correlativo LIKE ? OR cl.razon_social LIKE ?)');
      const likeValue = `%${filters.q}%`;
      values.push(likeValue, likeValue);
    }

    const whereClause = conditions.length > 0
      ? `WHERE ${conditions.join(' AND ')}`
      : '';

    const sql = `
      SELECT
        c.id,
        c.numero_correlativo,
        cl.razon_social  AS cliente_nombre,
        u.nombre_completo AS ejecutivo_nombre,
        c.monto_total,
        c.moneda,
        c.estado,
        c.fecha_emision,
        c.creado_en
      FROM cotizaciones c
      INNER JOIN clientes cl ON cl.id = c.id_cliente
      INNER JOIN usuarios u  ON u.id  = c.id_ejecutivo
      ${whereClause}
      ORDER BY c.creado_en DESC
    `;

    const [rows] = await pool.execute(sql, values);
    return rows;
  },

  // ---------------------------------------------------------------------------
  // updateStatus
  // Change the estado field of a quotation. Validates the transition first.
  //
  // @param   {number}  id          - Quotation primary key
  // @param   {string}  nuevoEstado - Target state string
  // @param   {string}  estadoActual - Current state (for transition validation)
  // @returns {boolean}             - true if the row was updated
  // ---------------------------------------------------------------------------
  async updateStatus(id, nuevoEstado, estadoActual) {
    // Validate that the requested transition is legal
    const allowedTransitions = STATE_TRANSITIONS[estadoActual] || [];

    if (!allowedTransitions.includes(nuevoEstado)) {
      throw new Error(
        `Invalid state transition: '${estadoActual}' → '${nuevoEstado}'. ` +
        `Allowed transitions from '${estadoActual}': [${allowedTransitions.join(', ')}]`
      );
    }

    const sql = `
      UPDATE cotizaciones SET estado = ? WHERE id = ? AND estado = ?
    `;

    // The AND estado = ? prevents race conditions where another request already changed the state
    const [result] = await pool.execute(sql, [nuevoEstado, id, estadoActual]);
    return result.affectedRows > 0;
  },

  // ---------------------------------------------------------------------------
  // approve
  // Record the Jefe's approval or rejection decision.
  // Enforces that the quotation is currently in "En revision" before accepting.
  //
  // @param   {number}  id            - Quotation primary key
  // @param   {number}  aprobadoPor   - User ID of the Jefe
  // @param   {string}  decision      - 'aprobada' | 'rechazada'
  // @param   {string}  obsAprobacion - Mandatory justification text
  // @returns {boolean}
  // ---------------------------------------------------------------------------
  async approve(id, aprobadoPor, decision, obsAprobacion) {
    // Map decision string to the corresponding state name
    const nuevoEstado = decision === 'aprobada'
      ? 'Aprobada internamente'
      : 'Rechazada';

    const sql = `
      UPDATE cotizaciones
      SET
        estado           = ?,
        aprobado_por     = ?,
        fecha_aprobacion = NOW(),
        obs_aprobacion   = ?
      WHERE id = ? AND estado = 'En revision'
    `;

    const [result] = await pool.execute(sql, [
      nuevoEstado,
      aprobadoPor,
      obsAprobacion || null,
      id,
    ]);

    return result.affectedRows > 0;
  },

  // ---------------------------------------------------------------------------
  // updatePdfPath
  // Persist the relative file path of the uploaded PDF document.
  //
  // @param {number} id      - Quotation primary key
  // @param {string} pdfRuta - Relative path from the project root
  // ---------------------------------------------------------------------------
  async updatePdfPath(id, pdfRuta) {
    const sql = `UPDATE cotizaciones SET pdf_ruta = ? WHERE id = ?`;
    const [result] = await pool.execute(sql, [pdfRuta, id]);
    return result.affectedRows > 0;
  },

  // ---------------------------------------------------------------------------
  // checkDuplicate
  // Detect potential duplicate quotations within the last 30 days for the same
  // client and a similar description (RF06 — duplicate detection).
  //
  // @param   {number}  id_cliente  - Client ID to search against
  // @param   {string}  descripcion - Description text for partial matching
  // @returns {Array<Object>}       - Potentially matching quotations (may be empty)
  // ---------------------------------------------------------------------------
  async checkDuplicate(id_cliente, descripcion) {
    // Extract first 50 characters of description as a rough similarity key
    const descSnippet = descripcion.substring(0, 50);

    const sql = `
      SELECT id, numero_correlativo, fecha_emision, estado
      FROM cotizaciones
      WHERE
        id_cliente   = ?
        AND descripcion  LIKE ?
        AND fecha_emision >= DATE_SUB(CURDATE(), INTERVAL 30 DAY)
      LIMIT 5
    `;

    const [rows] = await pool.execute(sql, [id_cliente, `%${descSnippet}%`]);
    return rows;
  },

  // Export constants for use in services
  VALID_STATES,
  STATE_TRANSITIONS,
};

module.exports = QuotationModel;
